# fly.toml app configuration file generated for cell-classifier-mlops on 2026-08-01T00:03:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cell-classifier-mlops'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile.serve'

[env]
  PORT = '8080'
  STUB_MODE = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
